enum RouteNames {
  HOME = 'HOME',
  COC_API_LOGIN = 'COC_API_LOGIN',
  MEMBERS = 'MEMBERS',
  ADD_MEMBER = 'ADD_MEMBER',
  EDIT_MEMBER = 'EDIT_MEMBER',
  CLAN_GAMES = 'CLAN_GAMES',
  ADD_CLAN_GAMES = 'ADD_CLAN_GAMES',
  CLAN_CAPITAL = 'CLAN_CAPITAL',
  CLAN_WARS = 'CLAN_WARS',
  CLAN_WAR_LEAGUES = 'CLAN_WAR_LEAGUES',
  SETTINGS = 'SETTINGS',
}

export default RouteNames;
